// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv2M66zpgjDo9ZJ6J8WaKQSXur4uVjf8k',
    appId: '1:251566626417:web:b59fab4330639240f36dd0',
    messagingSenderId: '251566626417',
    projectId: 'medihealth-6688f',
    authDomain: 'medihealth-6688f.firebaseapp.com',
    storageBucket: 'medihealth-6688f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAosga2ZQG0Qlu0VJr-O9GoAglw6F78pPY',
    appId: '1:251566626417:android:96d61aa633136681f36dd0',
    messagingSenderId: '251566626417',
    projectId: 'medihealth-6688f',
    storageBucket: 'medihealth-6688f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnBcZdrx8Gq2-81stlDnzVAs6A-CrQ1Wo',
    appId: '1:251566626417:ios:8a70fa1c7f59a431f36dd0',
    messagingSenderId: '251566626417',
    projectId: 'medihealth-6688f',
    storageBucket: 'medihealth-6688f.firebasestorage.app',
    iosBundleId: 'com.example.mediApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnBcZdrx8Gq2-81stlDnzVAs6A-CrQ1Wo',
    appId: '1:251566626417:ios:8a70fa1c7f59a431f36dd0',
    messagingSenderId: '251566626417',
    projectId: 'medihealth-6688f',
    storageBucket: 'medihealth-6688f.firebasestorage.app',
    iosBundleId: 'com.example.mediApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv2M66zpgjDo9ZJ6J8WaKQSXur4uVjf8k',
    appId: '1:251566626417:web:abbd1fa250f91a5ef36dd0',
    messagingSenderId: '251566626417',
    projectId: 'medihealth-6688f',
    authDomain: 'medihealth-6688f.firebaseapp.com',
    storageBucket: 'medihealth-6688f.firebasestorage.app',
  );
}
